server:
  port: 8080  # ????

spring:
  application:
    name: Spring Security # ????
  # redis????
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # ?????
    druid:
      min-idle: 5                           # ??????????????????????????????
      max-active: 20                        # ???????????????????????????
      max-wait: 60000                       # ???????????????????????????60000ms = 60?
      initial-size: 5                       # ?????????????
      connectTimeout: 30000                 # ????????????????????30000ms = 30?
      socketTimeout: 60000                  # ?????? socket ????????????60000ms = 60?
      timeBetweenEvictionRunsMillis: 60000  # ???????????????????60000ms = 60?
      minEvictableIdleTimeMillis: 300000    # ?????????????????????????????????300000ms = 5??
      validationQuery: SELECT 1 FROM DUAL   # ??????????? SQL
      testWhileIdle: true                   # ???????validationQuery????????
      testOnBorrow: false                   # ???????????????false ??????????
      testOnReturn: false                   # ???????????????false ??????????
      poolPreparedStatements: true          # ???? PreparedStatement?? PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 # ??PreparedStatement???????
      filters: stat,slf4j                   # ???????stat ???????slf4j ??????
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000 # ???????mergeSql=true ???? SQL ???slowSqlMillis=5000 ??? SQL ??? 5 ?

# mybatis-plus??
mybatis-plus:
  # ???????????????? XML ???????????
  # ???????? XML ???? "User" ?? "com.example.entity.User"
  typeAliasesPackage: sbs.getcry.**   # ???????

  # ?? Mapper XML ???????????????????? classpath ? mapper ?????? Mapper.xml ?????
  # ????? XML ???? SQL ??????????????
  mapper-locations: classpath:mapper/**/*.xml

  # ?????????????????????
  global-config:
    db-config:
      # ???????AUTO ????????????? MySQL ? AUTO_INCREMENT?
      # ?????? UUID????? ID??INPUT???????
      #id-type: AUTO

      # ????????????????????
      # ?????? User ??????? tbl_user
      #table-prefix: xxx_

      # ????????????????????????? 1?
      # ?????????????????????????????
      #logic-delete-value: 1

      # ??????????????????????????? 0
      # ????????? logic-delete-value = 1 ????????? 0 ???
      #logic-not-delete-value: 0

      # ??????????????????????????? deleted ??
      # ??? logic-delete-value ? logic-not-delete-value ????????????
      #logic-delete-field: deleted

      # ???????NOT_NULL ???????????????
      # ?????IGNORED?????????NOT_EMPTY??????????
      #field-strategy: NOT_NULL

  # MyBatis-Plus ????????? MyBatis ????
  configuration:
    map-underscore-to-camel-case: true # ?????????????true ??????? user_name ??????? userName, ?? true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     # ???????????? StdOutImpl ? SQL ????????,????????? SLF4J ???????????
